export default function PrivacyPage() {
  return (
    <div className="mx-auto flex w-full max-w-4xl flex-col gap-8 px-4 py-16">
      <section className="glass-panel rounded-3xl px-8 py-10">
        <p className="text-sm uppercase tracking-[0.2em] text-slate-400">
          Legal
        </p>
        <h1 className="mt-3 text-3xl font-semibold text-white">
          Privacy Policy
        </h1>
        <p className="mt-2 text-sm text-slate-400">Last updated: January 18, 2026</p>
      </section>

      <section className="glass-panel space-y-8 rounded-3xl px-8 py-10 text-sm text-slate-200 leading-relaxed">

        <p>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
          information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
          collection and use of information in accordance with this Privacy Policy.
        </p>

        {/* Interpretation & Definitions */}
        <div>
          <h2 className="text-lg font-semibold text-white mb-3">Interpretation and Definitions</h2>
          <h3 className="font-semibold text-white mb-2">Interpretation</h3>
          <p>
            The words whose initial letters are capitalized have meanings defined under the following conditions.
            The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <h3 className="font-semibold text-white mt-4 mb-2">Definitions</h3>
          <ul className="space-y-2 list-none">
            {[
              ["Account", "means a unique account created for You to access our Service or parts of our Service."],
              ["Affiliate", `means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.`],
              ["Application", "refers to Verified Sound, the software program provided by the Company."],
              ["Company", `(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Verified Sound.`],
              ["Cookies", "are small files placed on Your computer, mobile device or any other device by a website, containing details of Your browsing history."],
              ["Country", "refers to: Illinois, United States"],
              ["Device", "means any device that can access the Service such as a computer, a cell phone or a digital tablet."],
              ["Personal Data", "is any information that relates to an identified or identifiable individual."],
              ["Service", "refers to the Application or the Website or both."],
              ["Service Provider", "means any natural or legal person who processes the data on behalf of the Company."],
              ["Usage Data", "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself."],
              ["Website", "refers to Verified Sound, accessible from https://verifiedsoundar.com"],
              ["You", "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service."],
            ].map(([term, def]) => (
              <li key={term} className="flex gap-2">
                <span className="font-semibold text-white shrink-0">{term}:</span>
                <span>{def}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Collecting Data */}
        <div>
          <h2 className="text-lg font-semibold text-white mb-3">Collecting and Using Your Personal Data</h2>

          <h3 className="font-semibold text-white mb-2">Types of Data Collected</h3>
          <h4 className="font-medium text-slate-300 mb-1">Personal Data</h4>
          <p>While using Our Service, We may ask You to provide personally identifiable information including:</p>
          <ul className="mt-2 ml-4 list-disc space-y-1">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="font-medium text-slate-300 mt-4 mb-1">Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service. It may include information such as Your
            Device&apos;s Internet Protocol address, browser type, browser version, the pages of our Service that You visit,
            the time and date of Your visit, the time spent on those pages, and unique device identifiers.
          </p>

          <h4 className="font-medium text-slate-300 mt-4 mb-1">Tracking Technologies and Cookies</h4>
          <p>We use Cookies and similar tracking technologies to track activity on Our Service. We use:</p>
          <ul className="mt-2 ml-4 list-disc space-y-2">
            <li><span className="font-semibold text-white">Necessary / Essential Cookies</span> — Session Cookies essential to provide services and authenticate users.</li>
            <li><span className="font-semibold text-white">Cookies Policy / Notice Acceptance Cookies</span> — Persistent Cookies to identify if users have accepted cookies.</li>
            <li><span className="font-semibold text-white">Functionality Cookies</span> — Persistent Cookies to remember choices You make when using the Website.</li>
          </ul>
        </div>

        {/* Use of Data */}
        <div>
          <h3 className="font-semibold text-white mb-2">Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul className="mt-2 ml-4 list-disc space-y-1">
            <li><span className="font-semibold text-white">To provide and maintain our Service</span>, including to monitor the usage of our Service.</li>
            <li><span className="font-semibold text-white">To manage Your Account</span> and Your registration as a user of the Service.</li>
            <li><span className="font-semibold text-white">For the performance of a contract</span> for products, items or services You have purchased.</li>
            <li><span className="font-semibold text-white">To contact You</span> by email or other electronic communication regarding updates or services.</li>
            <li><span className="font-semibold text-white">To manage Your requests</span> to Us.</li>
            <li><span className="font-semibold text-white">For business transfers</span> — We may use Your information to evaluate or conduct a merger or sale of assets.</li>
            <li><span className="font-semibold text-white">For other purposes</span> such as data analysis, identifying usage trends, and improving our Service.</li>
          </ul>
        </div>

        {/* Retention */}
        <div>
          <h3 className="font-semibold text-white mb-2">Retention of Your Personal Data</h3>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in
            this Privacy Policy, or to comply with legal obligations, resolve disputes, and enforce our legal agreements.
          </p>
        </div>

        {/* Transfer */}
        <div>
          <h3 className="font-semibold text-white mb-2">Transfer of Your Personal Data</h3>
          <p>
            Your information may be transferred to and maintained on computers outside of Your state, province, country
            or other governmental jurisdiction. The Company will take all steps reasonably necessary to ensure Your data
            is treated securely.
          </p>
        </div>

        {/* Delete */}
        <div>
          <h3 className="font-semibold text-white mb-2">Delete Your Personal Data</h3>
          <p>
            You have the right to delete or request that We assist in deleting the Personal Data We have collected about
            You. You may do so by signing into Your Account and visiting the account settings section, or by contacting Us.
          </p>
        </div>

        {/* Disclosure */}
        <div>
          <h3 className="font-semibold text-white mb-2">Disclosure of Your Personal Data</h3>
          <h4 className="font-medium text-slate-300 mb-1">Business Transactions</h4>
          <p>If the Company is involved in a merger or asset sale, Your Personal Data may be transferred with prior notice.</p>
          <h4 className="font-medium text-slate-300 mt-3 mb-1">Law Enforcement</h4>
          <p>The Company may disclose Your Personal Data if required by law or in response to valid requests by public authorities.</p>
          <h4 className="font-medium text-slate-300 mt-3 mb-1">Other Legal Requirements</h4>
          <p>The Company may disclose Your Personal Data in good faith to comply with a legal obligation, protect the rights or property of the Company, or protect the personal safety of users.</p>
        </div>

        {/* Security */}
        <div>
          <h3 className="font-semibold text-white mb-2">Security of Your Personal Data</h3>
          <p>
            The security of Your Personal Data is important to Us. While We strive to use commercially acceptable means
            to protect Your Personal Data, We cannot guarantee its absolute security as no method of Internet transmission
            is 100% secure.
          </p>
        </div>

        {/* Third Party */}
        <div>
          <h2 className="text-lg font-semibold text-white mb-3">Detailed Information on Third-Party Processing</h2>
          <p>The Service Providers We use may have access to Your Personal Data, including:</p>
          <ul className="mt-2 ml-4 list-disc space-y-1">
            <li><span className="font-semibold text-white">Google Places</span> — collects location information for service functionality. Governed by <a href="https://www.google.com/intl/en/policies/privacy/" target="_blank" rel="noopener noreferrer" className="text-emerald-400 hover:underline">Google&apos;s Privacy Policy</a>.</li>
          </ul>
        </div>

        {/* Children */}
        <div>
          <h2 className="text-lg font-semibold text-white mb-2">Children&apos;s Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
            information from anyone under 13. If You are a parent or guardian and believe Your child has provided Us with
            Personal Data, please contact Us immediately.
          </p>
        </div>

        {/* Links */}
        <div>
          <h2 className="text-lg font-semibold text-white mb-2">Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites not operated by Us. We strongly advise You to review the
            Privacy Policy of every site You visit. We have no control over the content or privacy practices of any
            third-party sites.
          </p>
        </div>

        {/* Changes */}
        <div>
          <h2 className="text-lg font-semibold text-white mb-2">Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
            Privacy Policy on this page and updating the &quot;Last updated&quot; date. You are advised to review this
            Privacy Policy periodically for any changes.
          </p>
        </div>

        {/* Contact */}
        <div>
          <h2 className="text-lg font-semibold text-white mb-2">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="mt-2 ml-4 list-disc space-y-1">
            <li>By email: <a href="mailto:info@verifiedsoundar.com" className="text-emerald-400 hover:underline">info@verifiedsoundar.com</a></li>
            <li>By visiting: <a href="https://www.verifiedsoundar.com" className="text-emerald-400 hover:underline">www.verifiedsoundar.com</a></li>
          </ul>
        </div>

      </section>
    </div>
  );
}
